# Generated by Django 4.2.10 on 2024-08-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_remove_course_start_date_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], default='student', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.group', verbose_name='Группы'),
        ),
    ]
